re-enabling intergration tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -36,52 +36,52 @@ jobs:
           yamllint .
           ansible-lint
 
-  # integration:
-  #   name: Integration
-  #   runs-on: ${{ matrix.os }}
-  #   strategy:
-  #     matrix:
-  #       os:
-  #         - macos-latest
+  integration:
+    name: Integration
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os:
+          - macos-latest
 
-  #   steps:
-  #     - name: Check out the codebase.
-  #       uses: actions/checkout@v2
-  #       with:
-  #         path: ansible_collections/sculley/mac_setup
+    steps:
+      - name: Check out the codebase.
+        uses: actions/checkout@v2
+        with:
+          path: ansible_collections/sculley/mac_setup
 
-  #     - name: Uninstall GitHub Actions' built-in Homebrew.
-  #       run: tests/uninstall-homebrew.sh
+      - name: Uninstall GitHub Actions' built-in Homebrew.
+        run: tests/uninstall-homebrew.sh
 
-  #     - name: Uninstall GitHub Actions' built-in browser installs.
-  #       run: |
-  #         sudo rm -rf /Applications/Firefox.app
-  #         sudo rm -rf /Applications/Google\ Chrome.app
+      - name: Uninstall GitHub Actions' built-in browser installs.
+        run: |
+          sudo rm -rf /Applications/Firefox.app
+          sudo rm -rf /Applications/Google\ Chrome.app
 
-  #     - name: Install test dependencies.
-  #       run: |
-  #         sudo pip3 install --upgrade pip
-  #         sudo pip3 install ansible-core
+      - name: Install test dependencies.
+        run: |
+          sudo pip3 install --upgrade pip
+          sudo pip3 install ansible-core
 
-  #     - name: Set up the test environment.
-  #       run: |
-  #         cp tests/ansible.cfg ./ansible.cfg
-  #         cp tests/inventory ./inventory
-  #         ansible-galaxy collection install community.general
-  #         ansible-galaxy role install elliotweiser.osx-command-line-tools
+      - name: Set up the test environment.
+        run: |
+          cp tests/ansible.cfg ./ansible.cfg
+          cp tests/inventory ./inventory
+          ansible-galaxy collection install community.general
+          ansible-galaxy role install elliotweiser.osx-command-line-tools
 
-  #     - name: Test the playbook's syntax.
-  #       run: ansible-playbook tests/test.yml --syntax-check
+      - name: Test the playbook's syntax.
+        run: ansible-playbook tests/test.yml --syntax-check
 
-  #     - name: Test the playbook.
-  #       run: ansible-playbook tests/test.yml
-  #       env:
-  #         ANSIBLE_FORCE_COLOR: '1'
+      - name: Test the playbook.
+        run: ansible-playbook tests/test.yml
+        env:
+          ANSIBLE_FORCE_COLOR: '1'
 
-  #     - name: Idempotence check.
-  #       run: |
-  #         idempotence=$(mktemp)
-  #         ansible-playbook tests/test.yml | tee -a ${idempotence}
-  #         tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
-  #       env:
-  #         ANSIBLE_FORCE_COLOR: '1'
+      - name: Idempotence check.
+        run: |
+          idempotence=$(mktemp)
+          ansible-playbook tests/test.yml | tee -a ${idempotence}
+          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
+        env:
+          ANSIBLE_FORCE_COLOR: '1'
